--- !ruby/object:Jumpstart::Configuration
application_name: TurboNote
business_name: ''
domain: example.com
support_email: ''
default_from_email: Jumpstart <support@example.com>
business_address: ''
background_job_processor: async
email_provider: ''
personal_accounts: true
livereload: false
solargraph: false
register_with_account: false
